### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Trigus42/crunchyroll-dl#7] opened 2021-10-09 17:05 UTC
libtk8.6.so: cannot open shared object file: No such file or directory 
Falling back to manual input

+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > http://www.crunchyroll.com/jojos-bizarre-adventure
Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 482, in <module>
    w_anime.get_info()
  File "/home/esmailelbob/Downloads/main.py", line 165, in get_info
    "title": playlist_ie_return["title"],
TypeError: list indices must be integers or slices, not str

**Comment by compucat** [comment] 2021-10-09 23:54
Yup, having this issue as well.

**Comment by Trigus42** [comment] 2021-10-10 01:36
Please try out the `dev` branch. The issue should be fixed

**Closed as completed** 2021-10-14 18:27 UTC

**Comment by EsmailELBoBDev2** [comment] 2021-10-16 09:14
sorry for late reply but there is no `dev` branch, it's only one and it's master

**Comment by Trigus42** [comment] 2021-10-16 12:36
I already merged the branches. You can just pull the master branch again.

**Comment by EsmailELBoBDev2** [comment] 2021-10-18 10:40
well, still i get error:
```
esmailelbob in ~/Downloads 
$ python main.py                                                                                                                              19338ms 
libtk8.6.so: cannot open shared object file: No such file or directory 
Falling back to manual input

+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > https://www.crunchyroll.com/jojos-bizarre-adventure/episode-17-rohan-kishibes-adventure-715145?t=2
Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 556, in <module>
    main()
  File "/home/esmailelbob/Downloads/main.py", line 553, in main
    session(config, config_path, arguments, verbosity, use_filedialog)
  File "/home/esmailelbob/Downloads/main.py", line 377, in session
    w_anime.get_info()
  File "/home/esmailelbob/Downloads/main.py", line 147, in get_info
    playlist_ie_return = self.playlist_ie._real_extract(self.config["url"])
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/crunchyroll.py", line 665, in _real_extract
    show_id = self._match_id(url)
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 422, in _match_id
    assert m
AssertionError
esmailelbob in ~/Downloads 
$ python main.py                                                                                                                              46230ms 
libtk8.6.so: cannot open shared object file: No such file or directory 
Falling back to manual input

+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > 715145
Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 556, in <module>
    main()
  File "/home/esmailelbob/Downloads/main.py", line 553, in main
    session(config, config_path, arguments, verbosity, use_filedialog)
  File "/home/esmailelbob/Downloads/main.py", line 398, in session
    w_anime.config = config["anime"][list(config["anime"])[choice]]
IndexError: list index out of range
esmailelbob in ~/Downloads 
$ python main.py                                                                                                                               8688ms 
libtk8.6.so: cannot open shared object file: No such file or directory 
Falling back to manual input

+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > jojos-bizarre-adventure
Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 556, in <module>
    main()
  File "/home/esmailelbob/Downloads/main.py", line 553, in main
    session(config, config_path, arguments, verbosity, use_filedialog)
  File "/home/esmailelbob/Downloads/main.py", line 377, in session
    w_anime.get_info()
  File "/home/esmailelbob/Downloads/main.py", line 147, in get_info
    playlist_ie_return = self.playlist_ie._real_extract(self.config["url"])
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/crunchyroll.py", line 665, in _real_extract
    show_id = self._match_id(url)
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 422, in _match_id
    assert m
AssertionError
esmailelbob in ~/Downloads 
$ python main.py                                                                                                                               2580ms 
libtk8.6.so: cannot open shared object file: No such file or directory 
Falling back to manual input

+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > https://www.crunchyroll.com/jojos-bizarre-adventure
Could not access https://www.crunchyroll.com/jojos-bizarre-adventure. Please download the page manually.
Please enter the path of the html file > https://www.crunchyroll.com/jojos-bizarre-adventure
Traceback (most recent call last):
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 147, in get_info
    playlist_ie_return = self.playlist_ie._real_extract(self.config["url"])
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/crunchyroll.py", line 667, in _real_extract
    webpage = self._download_webpage(
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 798, in _download_webpage
    res = self._download_webpage_handle(
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/esmailelbob/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esmailelbob/Downloads/main.py", line 556, in <module>
    main()
  File "/home/esmailelbob/Downloads/main.py", line 553, in main
    session(config, config_path, arguments, verbosity, use_filedialog)
  File "/home/esmailelbob/Downloads/main.py", line 377, in session
    w_anime.get_info()
  File "/home/esmailelbob/Downloads/main.py", line 158, in get_info
    "urls": flattened_list(load_urls_from_html(self.config["html_path"]))
  File "/home/esmailelbob/Downloads/main.py", line 276, in load_urls_from_html
    with open(html_path, "r", encoding="utf-8") as html_file:
FileNotFoundError: [Errno 2] No such file or directory: 'https:/www.crunchyroll.com/jojos-bizarre-adventure'
esmailelbob in ~/Downloads 
```

**Comment by Trigus42** [comment] 2021-10-18 11:19
The problem is that CR uses Cloudflare, which is blocking your connection. You have to open `https://www.crunchyroll.com/jojos-bizarre-adventure` in your browser and download the htm/html file. Then you have to type in the path of that file.
For example:

```sh
root@DESKTOP-PSBB7H1:/mnt/e/user/Documents/GitHub/crunchyroll-dl# python3 main.py -nf
+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > https://www.crunchyroll.com/jojos-bizarre-adventure
Could not access https://www.crunchyroll.com/jojos-bizarre-adventure. Please download the page manually.
Please enter the path of the html file > '/mnt/e/user/Desktop/cr_jojo.htm'
Choose a download folder > /mnt/e/user/Desktop/
Type in output syntax; Leave blank for default > 
+-------+--------+---------+----------+
| Index | Season | Episode | Language |
+-------+--------+---------+----------+
|   0   |   4    |    1    |   jaJP   |
|   1   |   4    |    2    |   jaJP   |
|   2   |   4    |    3    |   jaJP   |
|   3   |   4    |    4    |   jaJP   |
|   4   |   4    |    5    |   jaJP   |
|   5   |   4    |    6    |   jaJP   |
|   6   |   4    |    7    |   jaJP   |
|   7   |   4    |    8    |   jaJP   |
|   8   |   4    |    9    |   jaJP   |
|   9   |   4    |    10   |   jaJP   |
|   10  |   4    |    11   |   jaJP   |
|   11  |   4    |    12   |   jaJP   |
|   12  |   4    |    13   |   jaJP   |
|   13  |   4    |    14   |   jaJP   |
|   14  |   4    |    15   |   jaJP   |
|   15  |   4    |    16   |   jaJP   |
|   16  |   4    |    17   |   jaJP   |
|   17  |   4    |    18   |   jaJP   |
|   18  |   4    |    19   |   jaJP   |
|   19  |   4    |    20   |   jaJP   |
|   20  |   4    |    21   |   jaJP   |
|   21  |   4    |    22   |   jaJP   |
|   22  |   4    |    23   |   jaJP   |
|   23  |   4    |    24   |   jaJP   |
|   24  |   4    |    25   |   jaJP   |
|   25  |   4    |    26   |   jaJP   |
|   26  |   4    |    27   |   jaJP   |
|   27  |   4    |    28   |   jaJP   |
|   28  |   4    |    29   |   jaJP   |
|   29  |   4    |    30   |   jaJP   |
|   30  |   4    |    31   |   jaJP   |
|   31  |   4    |    32   |   jaJP   |
|   32  |   4    |    33   |   jaJP   |
|   33  |   4    |    34   |   jaJP   |
|   34  |   4    |    35   |   jaJP   |
|   35  |   4    |    36   |   jaJP   |
|   36  |   4    |    37   |   jaJP   |
|   37  |   4    |    38   |   jaJP   |
|   38  |   4    |    39   |   jaJP   |
|   39  |   4    |    7    |   jaJP   |
|   40  |   4    |    7    |   jaJP   |
|   41  |   4    |    7    |   jaJP   |
|   42  |   3    |    1    |   jaJP   |
|   43  |   3    |    2    |   jaJP   |
|   44  |   3    |    3    |   jaJP   |
|   45  |   3    |    4    |   jaJP   |
|   46  |   3    |    5    |   jaJP   |
|   47  |   3    |    6    |   jaJP   |
|   48  |   3    |    7    |   jaJP   |
|   49  |   3    |    8    |   jaJP   |
|   50  |   3    |    9    |   jaJP   |
|   51  |   3    |    10   |   jaJP   |
|   52  |   3    |    11   |   jaJP   |
|   53  |   3    |    12   |   jaJP   |
|   54  |   3    |    13   |   jaJP   |
|   55  |   3    |    14   |   jaJP   |
|   56  |   3    |    15   |   jaJP   |
|   57  |   3    |    16   |   jaJP   |
|   58  |   3    |    17   |   jaJP   |
|   59  |   3    |    18   |   jaJP   |
|   60  |   3    |    19   |   jaJP   |
|   61  |   3    |    20   |   jaJP   |
|   62  |   3    |    21   |   jaJP   |
|   63  |   3    |    22   |   jaJP   |
|   64  |   3    |    23   |   jaJP   |
|   65  |   3    |    24   |   jaJP   |
|   66  |   3    |    25   |   jaJP   |
|   67  |   3    |    26   |   jaJP   |
|   68  |   3    |    27   |   jaJP   |
|   69  |   3    |    28   |   jaJP   |
|   70  |   3    |    29   |   jaJP   |
|   71  |   3    |    30   |   jaJP   |
|   72  |   3    |    31   |   jaJP   |
|   73  |   3    |    32   |   jaJP   |
|   74  |   3    |    33   |   jaJP   |
|   75  |   3    |    34   |   jaJP   |
|   76  |   3    |    35   |   jaJP   |
|   77  |   3    |    36   |   jaJP   |
|   78  |   3    |    37   |   jaJP   |
|   79  |   3    |    38   |   jaJP   |
|   80  |   3    |    39   |   jaJP   |
|   81  |   2    |    25   |   jaJP   |
|   82  |   2    |    26   |   jaJP   |
|   83  |   2    |    27   |   jaJP   |
|   84  |   2    |    28   |   jaJP   |
|   85  |   2    |    29   |   jaJP   |
|   86  |   2    |    30   |   jaJP   |
|   87  |   2    |    31   |   jaJP   |
|   88  |   2    |    32   |   jaJP   |
|   89  |   2    |    33   |   jaJP   |
|   90  |   2    |    34   |   jaJP   |
|   91  |   2    |    35   |   jaJP   |
|   92  |   2    |    36   |   jaJP   |
|   93  |   2    |    37   |   jaJP   |
|   94  |   2    |    38   |   jaJP   |
|   95  |   2    |    39   |   jaJP   |
|   96  |   2    |    40   |   jaJP   |
|   97  |   2    |    41   |   jaJP   |
|   98  |   2    |    42   |   jaJP   |
|   99  |   2    |    43   |   jaJP   |
|  100  |   2    |    44   |   jaJP   |
|  101  |   2    |    45   |   jaJP   |
|  102  |   2    |    46   |   jaJP   |
|  103  |   2    |    47   |   jaJP   |
|  104  |   2    |    48   |   jaJP   |
|  105  |   2    |    1    |   jaJP   |
|  106  |   2    |    2    |   jaJP   |
|  107  |   2    |    3    |   jaJP   |
|  108  |   2    |    4    |   jaJP   |
|  109  |   2    |    5    |   jaJP   |
|  110  |   2    |    6    |   jaJP   |
|  111  |   2    |    7    |   jaJP   |
|  112  |   2    |    8    |   jaJP   |
|  113  |   2    |    9    |   jaJP   |
|  114  |   2    |    10   |   jaJP   |
|  115  |   2    |    11   |   jaJP   |
|  116  |   2    |    12   |   jaJP   |
|  117  |   2    |    13   |   jaJP   |
|  118  |   2    |    14   |   jaJP   |
|  119  |   2    |    15   |   jaJP   |
|  120  |   2    |    16   |   jaJP   |
|  121  |   2    |    17   |   jaJP   |
|  122  |   2    |    18   |   jaJP   |
|  123  |   2    |    19   |   jaJP   |
|  124  |   2    |    20   |   jaJP   |
|  125  |   2    |    21   |   jaJP   |
|  126  |   2    |    22   |   jaJP   |
|  127  |   2    |    23   |   jaJP   |
|  128  |   2    |    24   |   jaJP   |
|  129  |   1    |    1    |   jaJP   |
|  130  |   1    |    2    |   jaJP   |
|  131  |   1    |    3    |   jaJP   |
|  132  |   1    |    1    |   jaJP   |
|  133  |   1    |    2    |   jaJP   |
|  134  |   1    |    3    |   jaJP   |
|  135  |   1    |    4    |   jaJP   |
|  136  |   1    |    5    |   jaJP   |
|  137  |   1    |    6    |   jaJP   |
|  138  |   1    |    7    |   jaJP   |
|  139  |   1    |    8    |   jaJP   |
|  140  |   1    |    9    |   jaJP   |
|  141  |   1    |    10   |   jaJP   |
|  142  |   1    |    11   |   jaJP   |
|  143  |   1    |    12   |   jaJP   |
|  144  |   1    |    13   |   jaJP   |
|  145  |   1    |    14   |   jaJP   |
|  146  |   1    |    15   |   jaJP   |
|  147  |   1    |    16   |   jaJP   |
|  148  |   1    |    17   |   jaJP   |
|  149  |   1    |    18   |   jaJP   |
|  150  |   1    |    19   |   jaJP   |
|  151  |   1    |    20   |   jaJP   |
|  152  |   1    |    21   |   jaJP   |
|  153  |   1    |    22   |   jaJP   |
|  154  |   1    |    23   |   jaJP   |
|  155  |   1    |    24   |   jaJP   |
|  156  |   1    |    25   |   jaJP   |
|  157  |   1    |    26   |   jaJP   |
+-------+--------+---------+----------+
Videos downloaded: []
Videos to download (Index) > 129-157
```

**Comment by EsmailELBoBDev2** [comment] 2021-10-19 09:20
Well, it does not catch it

```
$ python main.py -nf                                                                                                                         409347ms 
+----+-------+
| ID | Anime |
+----+-------+
+----+-------+
Choose an anime by entering it's ID or enter a URL > https://www.crunchyroll.com/jojos-bizarre-adventure
Could not access https://www.crunchyroll.com/jojos-bizarre-adventure. Please download the page manually.
Please enter the path of the html file > '/home/esmailelbob/Downloads/jojo.html'
+-------+--------+---------+----------+
| Index | Season | Episode | Language |
+-------+--------+---------+----------+
+-------+--------+---------+----------+
Try again? (y/N) > 
```
 my html: (.txt bcuz of github)
[jojo.html.txt](https://github.com/Trigus42/crunchyroll-dl/files/7371909/jojo.html.txt)

**Comment by Trigus42** [comment] 2021-10-19 12:24
That's weird. Do you have the latest version (https://github.com/Trigus42/crunchyroll-dl/commit/6e9d379aefc8852ad707be90279876187a8e1df9) and all requirements up-to date?

Using your html file it works for me:

```
user@DESKTOP-PSBB7H1:/mnt/e/user/Dokumente/GitHub/crunchyroll-dl$ python3 main.py -nf
+----+--------------------------+
| ID |          Anime           |
+----+--------------------------+
| 0  | JoJo's Bizarre Adventure |
+----+--------------------------+
Choose an anime by entering it's ID or enter a URL > https://www.crunchyroll.com/jojos-bizarre-adventure
Could not access https://www.crunchyroll.com/jojos-bizarre-adventure. Please download the page manually.
Please enter the path of the html file > '/mnt/e/user/Desktop/jojo.html.txt'
Choose a download folder > '/mnt/e/user/Desktop/'
Type in output syntax; Leave blank for default >      
+-------+--------+---------+----------+
| Index | Season | Episode | Language |
+-------+--------+---------+----------+
...
|  156  |   1    |    25   |   jaJP   |
|  157  |   1    |    26   |   jaJP   |
+-------+--------+---------+----------+
Videos downloaded: []
Videos to download (Index) >
```

**Comment by EsmailELBoBDev2** [comment] 2021-10-19 13:48
i did yes, i re-downloaded the script today alongside deps
